
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
    - ./frontend:/app
    - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db

volumes:
  node_modules: